version: "3"
services:
    # PHP 7.4 application
    laravel_8:
        build:
            args:
                user: sandro
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-7.4-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./Livro-de-Inspertores/:/var/www
        depends_on:
            - redis
            # - queue
        networks:
            - laravel-eti

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8180:80
        volumes:
            - ./Livro-de-Inspertores/:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-eti

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel-eti

    # queue
    # queue:
    #     build:
    #         args:
    #             user: sandro
    #             uid: 1000
    #         context: ./Livro-de-Inspertores/
    #         dockerfile: Dockerfile
    #     restart: unless-stopped
    #     command: "php artisan queue:work"
    #     volumes:
    #         - ./Livro-de-Inspertores/:/var/www
    #     depends_on:
    #         - redis
    #     networks:
    #         - laravel-eti

    # db mysql
    # mysql:
    #     image: mysql:5.7.22
    #     restart: unless-stopped
    #     environment:
    #         MYSQL_DATABASE: ${DB_DATABASE}
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_USER: ${DB_USERNAME}
    #     volumes:
    #         - ./.docker/mysql/dbdata:/var/lib/mysql
    #     ports:
    #         - 3388:3306
    #     networks:
    #         - laravel-eti

networks:
    laravel-eti:
        driver: bridge